/**
 * 「复古游戏机」像素图标集（用户 2026-09-28 提供的压缩包，96 个 16×16 图标 / 10 组）。
 *
 * ★ 本文件是**构建期生成**的数据（来源：图标包的 `maps.py`，用 `ast` 解析、绝不执行
 *   外来脚本）：每组是"组标题 + 一批图标"，每个图标带 **id**（`0101` = 第 1 组第 1 个，
 *   配上 `util/iconValue.ts` 的 `nb:` 前缀存进 `icon` 字段）、**名字**（选择器显示与搜索）、
 *   一个 **emoji 兜底**（导出侧暂用，见计划 §6）和 **16×16 像素网格**（运行时合成 SVG
 *   与 canvas 绘制共用同一份数据，不落第二份冗余的 SVG 字符串）。
 * ★ 网格字符就是 `PALETTE` 的键（外来数据里的键名保持原样）：`.` = 透明。
 * ★ 别手改这个文件 —— 要更新图标集，重跑生成脚本再提交。
 */

/** 图标包自带的调色板（复古游戏机 7 色；`.` 表示透明） */
export const PALETTE: Readonly<Record<string, string>> = {
  N: '#0F172A',
  C: '#192134',
  R: '#DC2626',
  B: '#2563EB',
  G: '#22C55E',
  Y: '#FACC15',
  W: '#E2E8F0',
};

export interface PixelIcon {
  /** 组内编号拼的 id（`0101`…`1006`）；存进 `icon` 字段时加 `nb:` 前缀 */
  id: string;
  /** 选择器里显示的名字（中文，来自图标包） */
  name: string;
  /** 自带的 emoji 兜底（导出侧暂用） */
  emoji: string;
  /** 16×16 像素网格，字符 = `PALETTE` 的键，`.` = 透明 */
  grid: readonly string[];
}

export interface PixelIconGroup {
  /** 组标题（图标包原样，如 "🏷️ 标签"） */
  title: string;
  icons: readonly PixelIcon[];
}

export const PIXEL_ICON_GROUPS: readonly PixelIconGroup[] = [
  {
    title: '🏷️ 标签',
    icons: [
      {
        id: '0101',
        name: '标签',
        emoji: '🏷️',
        grid: [
          '................',
          '................',
          '......RRRRRRRRR.',
          '.....RRRRRRRRRR.',
          '....RRRRRRRRRRR.',
          '...RRRRRRRRRRRR.',
          '..RRRWWRRRRRRRR.',
          '.RRRWWWWRRRRRRR.',
          '.RRRWWWWRRRRRRR.',
          '..RRRWWRRRRRRRR.',
          '...RRRRRRRRRRRR.',
          '....RRRRRRRRRRR.',
          '.....RRRRRRRRRR.',
          '......RRRRRRRRR.',
          '................',
          '................',
        ],
      },
      {
        id: '0102',
        name: '书签',
        emoji: '🔖',
        grid: [
          '................',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRRRRRRRR...',
          '...RRRR..RRRR...',
          '...RRR....RRR...',
          '...RR......RR...',
          '...R........R...',
        ],
      },
      {
        id: '0103',
        name: '图钉',
        emoji: '📌',
        grid: [
          '................',
          '................',
          '..RRRRRRRRRRRR..',
          '..RRRRRRRRRRRR..',
          '..RRRRRRRRRRRR..',
          '...RRRRRRRRRR...',
          '....RRRRRRRR....',
          '....WWWWWWWW....',
          '...WWWWWWWWWW...',
          '......WWWW......',
          '......WWWW......',
          '......WWWW......',
          '......WWWW......',
          '......WWWW......',
          '......WWWW......',
          '.......WW.......',
        ],
      },
      {
        id: '0104',
        name: '带笔锁',
        emoji: '🔏',
        grid: [
          '..............Y.',
          '...........YYYY.',
          '..........YYYY..',
          '.........YYYY...',
          '........YYYY....',
          '.......YYYY.....',
          '...WWW..YYY.....',
          '..WW.WW..YY.....',
          '..WW.WW.........',
          '..BBBBBBBBBB....',
          '..BBBBBBBBBB....',
          '..BBBBWWBBBB....',
          '..BBBBWWBBBB....',
          '..BBBBBBBBBB....',
          '..BBBBBBBBBB....',
          '................',
        ],
      },
      {
        id: '0105',
        name: '上锁',
        emoji: '🔐',
        grid: [
          '................',
          '.....WWWWWW.....',
          '....WW....WW....',
          '....WW....WW....',
          '....WW....WW....',
          '....WW....WW....',
          '..YYYYYYYYYYYY..',
          '..YYYYYYYYYYYY..',
          '..YYYYYNNYYYYY..',
          '..YYYYYNNYYYYY..',
          '..YYYYYNNYYYYY..',
          '..YYYYYNNYYYYY..',
          '..YYYYYNNYYYYY..',
          '..YYYYYYYYYYYY..',
          '..YYYYYYYYYYYY..',
          '................',
        ],
      },
    ],
  },
  {
    title: '⚠️ 优先级',
    icons: [
      {
        id: '0201',
        name: '红圆 · 最高紧急',
        emoji: '🔴',
        grid: [
          '................',
          '....RRRRRRRR....',
          '...RRRRRRRRRR...',
          '..RRRRRRRRRRRR..',
          '.RRRRRRRRRRRRRR.',
          '.RRRRRRRRRRRRRR.',
          'RRRRRRRRRRRRRRRR',
          'RRRRRRRRRRRRRRRR',
          'RRRRRRRRRRRRRRRR',
          'RRRRRRRRRRRRRRRR',
          '.RRRRRRRRRRRRRR.',
          '.RRRRRRRRRRRRRR.',
          '..RRRRRRRRRRRR..',
          '...RRRRRRRRRR...',
          '....RRRRRRRR....',
          '................',
        ],
      },
      {
        id: '0202',
        name: '橙圆 · 高优先级',
        emoji: '🟠',
        grid: [
          '................',
          '....oooooooo....',
          '...oooooooooo...',
          '..oooooooooooo..',
          '.oooooooooooooo.',
          '.oooooooooooooo.',
          'oooooooooooooooo',
          'oooooooooooooooo',
          'oooooooooooooooo',
          'oooooooooooooooo',
          '.oooooooooooooo.',
          '.oooooooooooooo.',
          '..oooooooooooo..',
          '...oooooooooo...',
          '....oooooooo....',
          '................',
        ],
      },
      {
        id: '0203',
        name: '黄圆 · 中优先级',
        emoji: '🟡',
        grid: [
          '................',
          '....YYYYYYYY....',
          '...YYYYYYYYYY...',
          '..YYYYYYYYYYYY..',
          '.YYYYYYYYYYYYYY.',
          '.YYYYYYYYYYYYYY.',
          'YYYYYYYYYYYYYYYY',
          'YYYYYYYYYYYYYYYY',
          'YYYYYYYYYYYYYYYY',
          'YYYYYYYYYYYYYYYY',
          '.YYYYYYYYYYYYYY.',
          '.YYYYYYYYYYYYYY.',
          '..YYYYYYYYYYYY..',
          '...YYYYYYYYYY...',
          '....YYYYYYYY....',
          '................',
        ],
      },
      {
        id: '0204',
        name: '绿圆 · 低 / 正常',
        emoji: '🟢',
        grid: [
          '................',
          '....GGGGGGGG....',
          '...GGGGGGGGGG...',
          '..GGGGGGGGGGGG..',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          'GGGGGGGGGGGGGGGG',
          'GGGGGGGGGGGGGGGG',
          'GGGGGGGGGGGGGGGG',
          'GGGGGGGGGGGGGGGG',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '..GGGGGGGGGGGG..',
          '...GGGGGGGGGG...',
          '....GGGGGGGG....',
          '................',
        ],
      },
      {
        id: '0205',
        name: '蓝圆 · 待评估',
        emoji: '🔵',
        grid: [
          '................',
          '....BBBBBBBB....',
          '...BBBBBBBBBB...',
          '..BBBBBBBBBBBB..',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          'BBBBBBBBBBBBBBBB',
          'BBBBBBBBBBBBBBBB',
          'BBBBBBBBBBBBBBBB',
          'BBBBBBBBBBBBBBBB',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '..BBBBBBBBBBBB..',
          '...BBBBBBBBBB...',
          '....BBBBBBBB....',
          '................',
        ],
      },
      {
        id: '0206',
        name: '黑圆 · 冻结 / 暂停',
        emoji: '⚫',
        grid: [
          '................',
          '....WWWWWWWW....',
          '...WNNNNNNNNW...',
          '..WNNNNNNNNNNW..',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          'WNNNNNNNNNNNNNNW',
          'WNNNNNNNNNNNNNNW',
          'WNNNNNNNNNNNNNNW',
          'WNNNNNNNNNNNNNNW',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '..WNNNNNNNNNNW..',
          '...WNNNNNNNNW...',
          '....WWWWWWWW....',
          '................',
        ],
      },
      {
        id: '0207',
        name: '火焰 · 紧急燃点任务',
        emoji: '🔥',
        grid: [
          '................',
          '.........R......',
          '........RRR.....',
          '.......RRRR.....',
          '......RRRRR.....',
          '.....RRRRRR.....',
          '....RRRRRRRR....',
          '...RRRRRRRRRR...',
          '...RRRYYYYRRR...',
          '..RRRRYYYYRRRR..',
          '..RRRRYYYYRRRR..',
          '..RRRYYYYYYRRR..',
          '..RRRYYYYYYRRR..',
          '..RRRRRYYRRRRR..',
          '..RRRRRRRRRRRR..',
          '................',
        ],
      },
    ],
  },
  {
    title: '📋 任务',
    icons: [
      {
        id: '0301',
        name: '对勾 · 已完成',
        emoji: '✅',
        grid: [
          '................',
          '................',
          '................',
          '.............GG.',
          '............GGG.',
          '...........GGG..',
          '..........GGG...',
          '.........GGG....',
          '.GG.....GGG.....',
          '.GGG...GGG......',
          '..GGG.GGG.......',
          '...GGGGG........',
          '....GGG.........',
          '.....G..........',
          '................',
          '................',
        ],
      },
      {
        id: '0302',
        name: '方框勾选',
        emoji: '☑️',
        grid: [
          '................',
          '................',
          '..WWWWWWWWWWWW..',
          '..W..........W..',
          '..W.......GG.W..',
          '..W......GGG.W..',
          '..W.....GGG..W..',
          '..W....GGG...W..',
          '..W.GG.GGG...W..',
          '..W.GGGG.....W..',
          '..W..GG......W..',
          '..W..........W..',
          '..W..........W..',
          '..WWWWWWWWWWWW..',
          '................',
          '................',
        ],
      },
      {
        id: '0303',
        name: '空白复选框 · 待办',
        emoji: '☐',
        grid: [
          '................',
          '................',
          '..WWWWWWWWWWWW..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..W..........W..',
          '..WWWWWWWWWWWW..',
          '................',
          '................',
        ],
      },
      {
        id: '0304',
        name: '备忘录',
        emoji: '📝',
        grid: [
          '................',
          '.WWWWWWWWW......',
          '.WWWWWWWWW......',
          '.WNNNNNNNW..YY..',
          '.WWWWWWWWW.YYY..',
          '.WNNNNNNNW.YY...',
          '.WWWWWWWWWYY....',
          '.WNNNNNNNWY.....',
          '.WWWWWWWWW......',
          '.WNNNNNNNW......',
          '.WWWWWWWWW......',
          '.WNNNNNNNW......',
          '.WWWWWWWWW......',
          '.WWWWWWWWW......',
          '.WWWWWWWWW......',
          '................',
        ],
      },
      {
        id: '0305',
        name: '剪贴板清单',
        emoji: '📋',
        grid: [
          '......BBBB......',
          '.....BBBBBB.....',
          '..BBBBBBBBBBBB..',
          '..BWWWWWWWWWWB..',
          '..BWWWWWWWWWWB..',
          '..BWNNNNNNNNWB..',
          '..BWNNNNNNNNWB..',
          '..BWWWWWWWWWWB..',
          '..BWNNNNNNNNWB..',
          '..BWNNNNNNNNWB..',
          '..BWWWWWWWWWWB..',
          '..BWNNNNNNNNWB..',
          '..BWNNNNNNNNWB..',
          '..BWWWWWWWWWWB..',
          '..BBBBBBBBBBBB..',
          '................',
        ],
      },
      {
        id: '0306',
        name: '螺旋日历',
        emoji: '🗓️',
        grid: [
          '...W...W...W....',
          '...W...W...W....',
          '...W...W...W....',
          '.RRWRRRWRRRWRR..',
          '.RRRRRRRRRRRRR..',
          '.RRRRRRRRRRRRR..',
          '.WWWWWWWWWWWWW..',
          '.WNNWNNWNNWNNW..',
          '.WNNWNNWNNWNNW..',
          '.WWWWWWWWWWWWW..',
          '.WNNWNNWNNWNNW..',
          '.WNNWNNWNNWNNW..',
          '.WWWWWWWWWWWWW..',
          '.WGGWNNWNNWNNW..',
          '.WWWWWWWWWWWWW..',
          '................',
        ],
      },
      {
        id: '0307',
        name: '日历',
        emoji: '📅',
        grid: [
          '...BB......BB...',
          '...BB......BB...',
          '.RRRRRRRRRRRRR..',
          '.RRRRRRRRRRRRR..',
          '.RRRRRRRRRRRRR..',
          '.RRRRRRRRRRRRR..',
          '.WWWWWWWWWWWWW..',
          '.WNNWNNWNNWNNW..',
          '.WNNWNNWNNWNNW..',
          '.WWWWWWWWWWWWW..',
          '.WNNWNNWNNWNNW..',
          '.WNNWNNWNNWNNW..',
          '.WWWWWWWWWWWWW..',
          '.WNNWNNWNNGGNW..',
          '.WWWWWWWWWWWWW..',
          '................',
        ],
      },
      {
        id: '0308',
        name: '沙漏 · 进行中',
        emoji: '⏳',
        grid: [
          '................',
          '.BBBBBBBBBBBBB..',
          '.YYYYYYYYYYYYY..',
          '..YWWWWWWWWWY...',
          '...YWWWWWWWY....',
          '....YWWWWWY.....',
          '.....YWWWY......',
          '......YWY.......',
          '......YWY.......',
          '.....YWWWY......',
          '....YWWWWWY.....',
          '...YWWWWWWWY....',
          '..YWWWWWWWWWY...',
          '.YYYYYYYYYYYYY..',
          '.BBBBBBBBBBBBB..',
          '................',
        ],
      },
      {
        id: '0309',
        name: '闹钟 · 截止提醒',
        emoji: '⏰',
        grid: [
          '..WW........WW..',
          '...WW......WW...',
          '....RRRRRRRR....',
          '..RRRRRRRRRRRR..',
          '.RRRRRRRRRRRRRR.',
          'RRRRRRRRRRRRRRRR',
          'RRRRWWWWWWWWRRRR',
          'RRRWWWNWWWWWWRRR',
          'RRRWWWNNNWWWWRRR',
          'RRRWWWNWWWWWWRRR',
          'RRRWWWWWWWWWWRRR',
          'RRRRWWWWWWWWRRRR',
          'RRRRRRRRRRRRRRRR',
          '.RRRRRRRRRRRRRR.',
          '..RRRRRRRRRRRR..',
          '....RRRRRRRR....',
        ],
      },
      {
        id: '0310',
        name: '循环箭头 · 重复任务',
        emoji: '🔄',
        grid: [
          '................',
          '...........BBB..',
          '.....BBBBBBBBBB.',
          '...BBB.....BBBB.',
          '..BBB......BBB..',
          '..BB........BB..',
          '.BB..........BB.',
          '.BB..........BB.',
          '.BB..........BB.',
          '.BB..........BB.',
          '..BB........BB..',
          '..BBB......BBB..',
          '...BBBBBBBBB....',
          '.....BBBBBB.....',
          '................',
          '................',
        ],
      },
      {
        id: '0311',
        name: '靶心 · 目标任务',
        emoji: '🎯',
        grid: [
          '................',
          '.....RRRRRR.....',
          '...RRRRRRRRRR...',
          '..RRRWWWWWWRRR..',
          '.RRRWWWWWWWWRRR.',
          '.RRWWWWWWWWWWRR.',
          'RRRWWWRRRRWWWRRR',
          'RRWWWRRRRRRWWWRR',
          'RRWWWRRRRRRWWWRR',
          'RRRWWWRRRRWWWRRR',
          '.RRWWWWWWWWWWRR.',
          '.RRRWWWWWWWWRRR.',
          '..RRRWWWWWWRRR..',
          '...RRRRRRRRRR...',
          '.....RRRRRR.....',
          '................',
        ],
      },
      {
        id: '0312',
        name: '收件盘 · 待接收',
        emoji: '📥',
        grid: [
          '................',
          '.......GG.......',
          '.......GG.......',
          '.......GG.......',
          '.......GG.......',
          '....GGGGGGGG....',
          '.....GGGGGG.....',
          '......GGGG......',
          '.......GG.......',
          '................',
          '.BBBBBBBBBBBBBB.',
          '.B............B.',
          '.B............B.',
          '.B............B.',
          '.BBBBBBBBBBBBBB.',
          '................',
        ],
      },
      {
        id: '0313',
        name: '发件盘 · 已交付',
        emoji: '📤',
        grid: [
          '................',
          '.......RR.......',
          '......RRRR......',
          '.....RRRRRR.....',
          '....RRRRRRRR....',
          '.......RR.......',
          '.......RR.......',
          '.......RR.......',
          '.......RR.......',
          '................',
          '.BBBBBBBBBBBBBB.',
          '.B............B.',
          '.B............B.',
          '.B............B.',
          '.BBBBBBBBBBBBBB.',
          '................',
        ],
      },
    ],
  },
  {
    title: '🚩 旗帜',
    icons: [
      {
        id: '0401',
        name: '三角红旗 · 标记重点',
        emoji: '🚩',
        grid: [
          '................',
          '..WWRRRRRRRRRRR.',
          '..WWRRRRRRRRRR..',
          '..WWRRRRRRRRR...',
          '..WWRRRRRRRR....',
          '..WWRRRRRRR.....',
          '..WWRRRRRR......',
          '..WWRRRRR.......',
          '..WWRRRR........',
          '..WW............',
          '..WW............',
          '..WW............',
          '..WW............',
          '..WW............',
          '..WW............',
          '................',
        ],
      },
      {
        id: '0402',
        name: '方格旗 · 任务完成 / 终点',
        emoji: '🏁',
        grid: [
          '................',
          '.WWWWNNWWNNWWNN.',
          '.WWWWNNWWNNWWNN.',
          '.WWNNWWNNWWNNWW.',
          '.WWNNWWNNWWNNWW.',
          '.WWWWNNWWNNWWNN.',
          '.WWWWNNWWNNWWNN.',
          '.WWNNWWNNWWNNWW.',
          '.WWNNWWNNWWNNWW.',
          '.WWWWNNWWNNWWNN.',
          '.WWWWNNWWNNWWNN.',
          '.WW.............',
          '.WW.............',
          '.WW.............',
          '.WW.............',
          '................',
        ],
      },
      {
        id: '0403',
        name: '黑旗 · 阻塞 / 风险',
        emoji: '🏴',
        grid: [
          '................',
          '.WWWWWWWWWWWWWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWNNNNNNNNNNWW.',
          '.WWWWWWWWWWWWWW.',
          '.WW.............',
          '.WW.............',
          '.WW.............',
          '.WW.............',
          '................',
        ],
      },
      {
        id: '0404',
        name: '白旗 · 搁置',
        emoji: '🏳️',
        grid: [
          '................',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BBWWWWWWWWWWWW.',
          '.BB.............',
          '.BB.............',
          '.BB.............',
          '.BB.............',
          '.BB.............',
          '................',
        ],
      },
    ],
  },
  {
    title: '⭐ 星星',
    icons: [
      {
        id: '0501',
        name: '实心星 · 收藏重点',
        emoji: '⭐',
        grid: [
          '................',
          '.......YY.......',
          '......YYYY......',
          '......YYYY......',
          '.....YYYYYY.....',
          '.....YYYYYY.....',
          'YYYYYYYYYYYYYYYY',
          '.YYYYYYYYYYYYYY.',
          '..YYYYYYYYYYYY..',
          '..YYYYYYYYYYYY..',
          '...YYYYYYYYYY...',
          '...YYYY..YYYY...',
          '..YYYY....YYYY..',
          '..YYY......YYY..',
          '.YYY........YYY.',
          '.YY..........YY.',
        ],
      },
      {
        id: '0502',
        name: '闪光星 · 亮点 / 里程碑',
        emoji: '🌟',
        grid: [
          '..W..........W..',
          '.WWW........WWW.',
          '..W..........W..',
          '................',
          '.......YY.......',
          '.......YY.......',
          '......YYYY......',
          '......YYYY......',
          '...YYYYYYYYYY...',
          '...YYYYYYYYYY...',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '.....YYYYYY.....',
          '.....YY..YY.....',
          '....YY....YY....',
          '....YY....YY....',
        ],
      },
      {
        id: '0503',
        name: '闪烁星光',
        emoji: '✨',
        grid: [
          '................',
          '.....Y......Y...',
          '.....Y......Y...',
          '.....Y....YYYYY.',
          '....YYY....Y....',
          '....YYY....Y....',
          '.YYYYYYYYY......',
          '....YYY.........',
          '....YYY.........',
          '.....Y..........',
          '.....Y......Y...',
          '............Y...',
          '..........YYYYY.',
          '............Y...',
          '............Y...',
          '................',
        ],
      },
      {
        id: '0504',
        name: '眩晕星',
        emoji: '💫',
        grid: [
          '................',
          '................',
          '....BBBBBBBB....',
          '..BB........BB..',
          '.B............B.',
          'B..............B',
          'B......YY......B',
          'B....YYYYYY....B',
          'B...YYYYYYYY...B',
          'B....YYYYYY....B',
          '.B....YYYY....B.',
          '..BB........BB..',
          '....BBBBBBBB....',
          '................',
          '................',
          '................',
        ],
      },
      {
        id: '0505',
        name: '奖杯 · 成果奖励',
        emoji: '🏆',
        grid: [
          '................',
          '....YYYYYYYY....',
          '.YY.YYYYYYYY.YY.',
          '.YY.YYYYYYYY.YY.',
          '.YY.YYYYYYYY.YY.',
          '..Y.YYYYYYYY.Y..',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '.....YYYYYY.....',
          '......YYYY......',
          '.......YY.......',
          '.......YY.......',
          '....YYYYYYYY....',
          '...NNNNNNNNNN...',
          '...NNNNNNNNNN...',
          '................',
        ],
      },
    ],
  },
  {
    title: '👤 人物',
    icons: [
      {
        id: '0601',
        name: '男程序员',
        emoji: '👨‍💻',
        grid: [
          '................',
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NYYNNYYN....',
          '....NYYYYYYN....',
          '.....YYYYYY.....',
          '...BBBBBBBBBB...',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '.WWWWWWWWWWWWWW.',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '.NNNNNNNNNNNNNN.',
        ],
      },
      {
        id: '0602',
        name: '女程序员',
        emoji: '👩‍💻',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '...NNYYYYYYNN...',
          '...NNYYNNYYNN...',
          '...NNYYYYYYNN...',
          '...NNYYYYYYNN...',
          '...RRRRRRRRRR...',
          '..RRRRRRRRRRRR..',
          '..RRRRRRRRRRRR..',
          '..RRRRRRRRRRRR..',
          '.WWWWWWWWWWWWWW.',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '.NNNNNNNNNNNNNN.',
        ],
      },
      {
        id: '0603',
        name: '办公室职员',
        emoji: '🧑‍💼',
        grid: [
          '................',
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NYYNNYYN....',
          '....NYYYYYYN....',
          '.....YYYYYY.....',
          '...NNNNNNNNNN...',
          '..NNNWWWWWWNNN..',
          '..NNWWWRRWWWNN..',
          '..NNWWWRRWWWNN..',
          '..NNWWWRRWWWNN..',
          '..NNNWWWWWWNNN..',
          '...NNNNNNNNNN...',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '0604',
        name: '工人',
        emoji: '👷',
        grid: [
          '................',
          '.....YYYYYY.....',
          '....YYYYYYYY....',
          '..YYYYYYYYYYYY..',
          '....YYNYYNYY....',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '...YYYYYYYYYY...',
          '..YYYYYYYYYYYY..',
          '..YYYYNYYNYYYY..',
          '..YYYYNYYNYYYY..',
          '..YYYYYYYYYYYY..',
          '..YYYYYYYYYYYY..',
          '...YYYYYYYYYY...',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '0605',
        name: '技工',
        emoji: '🧑‍🔧',
        grid: [
          '................',
          '....NNNNNN......',
          '...NNNNNNNN.....',
          '...NYYNNYYN.....',
          '...NYYYYYYN.....',
          '....YYYYYY......',
          '..GGGGGGGGGG....',
          '.GGGGGGGGGGGG...',
          '.GGGGGGGGGGGG...',
          '.GGGGGGGGGGGG.YY',
          '.GGGGGGGGGGGGYYY',
          '.GGGGGGGGGGGGYY.',
          '.GGGGGGGGGGGGY..',
          '..GGGGGGGGGG.Y..',
          '...GG....GG.Y...',
          '...GG....GG.....',
        ],
      },
      {
        id: '0606',
        name: '握手 · 协作',
        emoji: '🤝',
        grid: [
          '................',
          '................',
          '................',
          '.....WW..YY.....',
          '...WWWWWWWWWWW..',
          '..WWWWWWWWWWWWW.',
          '..WWWWWYYYWWWWW.',
          '..WWWWWWWWWWWWW.',
          '..WWWWWWWWWWWWW.',
          '..WWWWWYYYWWWWW.',
          '..WWWWWWWWWWWWW.',
          '...WWWWWWWWWWW..',
          '.....WW..YY.....',
          '................',
          '................',
          '................',
        ],
      },
    ],
  },
  {
    title: '♾️ 符号',
    icons: [
      {
        id: '0701',
        name: '齿轮 · 配置 / bug / 开发',
        emoji: '⚙️',
        grid: [
          '................',
          '.......WW.......',
          '....W..WW..W....',
          '....WWWWWWWW....',
          '..WWWWWWWWWWWW..',
          '..WWWW....WWWW..',
          'WWWWWW....WWWWWW',
          'WWWW........WWWW',
          'WWWW........WWWW',
          'WWWWWW....WWWWWW',
          '..WWWW....WWWW..',
          '..WWWWWWWWWWWW..',
          '....WWWWWWWW....',
          '....W..WW..W....',
          '.......WW.......',
          '................',
        ],
      },
      {
        id: '0702',
        name: '叉号 · 失败 / 取消',
        emoji: '❌',
        grid: [
          '................',
          '................',
          '.RR..........RR.',
          '..RR........RR..',
          '...RR......RR...',
          '....RR....RR....',
          '.....RR..RR.....',
          '......RRRR......',
          '......RRRR......',
          '.....RR..RR.....',
          '....RR....RR....',
          '...RR......RR...',
          '..RR........RR..',
          '.RR..........RR.',
          '................',
          '................',
        ],
      },
      {
        id: '0703',
        name: '问号 · 待确认',
        emoji: '❓',
        grid: [
          '................',
          '................',
          '....BBBBBB......',
          '...BBBBBBBB.....',
          '..BBB....BBB....',
          '..BB......BB....',
          '..........BB....',
          '.........BBB....',
          '........BBB.....',
          '.......BBB......',
          '......BBB.......',
          '......BB........',
          '................',
          '......BB........',
          '......BB........',
          '................',
        ],
      },
      {
        id: '0704',
        name: '感叹号 · 警告',
        emoji: '❗',
        grid: [
          '................',
          '................',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '......RRRR......',
          '................',
          '......RRRR......',
          '......RRRR......',
          '................',
          '................',
        ],
      },
      {
        id: '0705',
        name: '放大镜 · 调研 / 审查',
        emoji: '🔍',
        grid: [
          '................',
          '....BBBBBB......',
          '..BBBBBBBBBB....',
          '.BBBBWW..BBBB...',
          '.BBBWW....BBB...',
          'BBBWW......BBB..',
          'BBB........BBB..',
          'BBB........BBB..',
          '.BBB......BBB...',
          '.BBBB....BBBB...',
          '..BBBBBBBBBB....',
          '....BBBBBB......',
          '..........BBB...',
          '...........BBB..',
          '............BBB.',
          '.............BB.',
        ],
      },
      {
        id: '0706',
        name: '柱状图',
        emoji: '📊',
        grid: [
          '................',
          '................',
          '................',
          '...........YY...',
          '...........YY...',
          '.....GG....YY...',
          '.....GG....YY...',
          '.....GG....YY...',
          '..BB.GG....YY...',
          '..BB.GG....YY...',
          '..BB.GG..RRYY...',
          '..BB.GG..RRYY...',
          '..BB.GG..RRYY...',
          '..BB.GG..RRYY...',
          '..NNNNNNNNNNNN..',
          '................',
        ],
      },
      {
        id: '0707',
        name: '上升图表',
        emoji: '📈',
        grid: [
          '................',
          '................',
          '..........GGGG..',
          '..........GGGGG.',
          '.........GGGG...',
          '........GGG.....',
          '.......GGG......',
          '......GGG.......',
          '.....GGG........',
          '....GGG.........',
          '...GGG..........',
          '..GGG...........',
          '.GGG............',
          '.GG.............',
          '..NNNNNNNNNNNN..',
          '................',
        ],
      },
      {
        id: '0708',
        name: '下降图表',
        emoji: '📉',
        grid: [
          '................',
          '................',
          '.RR.............',
          '.RRR............',
          '..RRR...........',
          '...RRR..........',
          '....RRR.........',
          '.....RRR........',
          '......RRR.......',
          '.......RRR......',
          '........RRR.....',
          '.........RRR....',
          '..........RRRR..',
          '..........RRRRR.',
          '..NNNNNNNNNNNN..',
          '................',
        ],
      },
      {
        id: '0709',
        name: '右箭头 · 流转',
        emoji: '➡️',
        grid: [
          '................',
          '................',
          '................',
          '................',
          '.........BB.....',
          '..........BB....',
          '...........BB...',
          'BBBBBBBBBBBBBBBB',
          'BBBBBBBBBBBBBBBB',
          '...........BB...',
          '..........BB....',
          '.........BB.....',
          '................',
          '................',
          '................',
          '................',
        ],
      },
    ],
  },
  {
    title: '💼 办公',
    icons: [
      {
        id: '0801',
        name: '公文包',
        emoji: '💼',
        grid: [
          '................',
          '.....WWWWWW.....',
          '.....W....W.....',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.NNNNNNNNNNNNNN.',
          '.BBBBBYYYYBBBBB.',
          '.BBBBBYYYYBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.NNNNNNNNNNNNNN.',
          '................',
          '................',
        ],
      },
      {
        id: '0802',
        name: '文件夹',
        emoji: '📁',
        grid: [
          '................',
          '................',
          '..YYYYYY........',
          '..YYYYYYYYYYYY..',
          '..YYYYYYYYYYYY..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '................',
          '................',
        ],
      },
      {
        id: '0803',
        name: '打开文件夹',
        emoji: '📂',
        grid: [
          '................',
          '................',
          '..YYYYYY........',
          '..YYYYYYYYYYYY..',
          '..YYYYYYYYYYYY..',
          '.BBBBBBBBBBBBBB.',
          '..BBBBBBBBBBBBB.',
          '..BBBBBBBBBBBBB.',
          '...BBBBBBBBBBBB.',
          '...BBBBBBBBBBBB.',
          '....BBBBBBBBBBB.',
          '....BBBBBBBBBBB.',
          '.....BBBBBBBBBB.',
          '.....BBBBBBBBBB.',
          '................',
          '................',
        ],
      },
      {
        id: '0804',
        name: '分类索引夹',
        emoji: '🗂️',
        grid: [
          '................',
          '..YYYYY...YYYYY.',
          '..YYYYY...YYYYY.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBYYYYYYYYBBB.',
          '.BBBYYYYYYYYBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBYYYYYYYYBBB.',
          '.BBBYYYYYYYYBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBYYYYYYYYBBB.',
          '.BBBYYYYYYYYBBB.',
          '.BBBBBBBBBBBBBB.',
          '................',
          '................',
        ],
      },
      {
        id: '0805',
        name: '卡片档案盒',
        emoji: '🗃️',
        grid: [
          '................',
          '..WW..WW..WW....',
          '..WW..WW..WW....',
          '..WW..WW..WW....',
          '..WW..WW..WW....',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.GGGGGGGGGGGGGG.',
          '.NNNNNNNNNNNNNN.',
          '................',
        ],
      },
      {
        id: '0806',
        name: '空白文档',
        emoji: '📄',
        grid: [
          '................',
          '..WWWWWWWWWW....',
          '..WWWWWWWWWWW...',
          '..WWWWWWWWWWWWN.',
          '..WWWWWWWWWWWWNN',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '................',
        ],
      },
      {
        id: '0807',
        name: '分页文档',
        emoji: '📑',
        grid: [
          '................',
          '.WWWWWWWWWWWWYY.',
          '.WWWWWWWWWWWWYY.',
          '.WWWWWWWWWWWWYY.',
          '.WWWWWWWWWWWWYY.',
          '.WNNNNNNNNNNW...',
          '.WWWWWWWWWWWW...',
          '.WNNNNNNNNNNW...',
          '.WWWWWWWWWWWW...',
          '.WNNNNNNNNNNW...',
          '.WWWWWWWWWWWW...',
          '.WNNNNNNNNNNW...',
          '.WWWWWWWWWWWW...',
          '.WNNNNNNNNNNW...',
          '.WWWWWWWWWWWW...',
          '................',
        ],
      },
      {
        id: '0808',
        name: '钢笔',
        emoji: '✒️',
        grid: [
          '.....BBBBBB.....',
          '.....BBBBBB.....',
          '......WWWW......',
          '.....WWWWWW.....',
          '.....WWYYWW.....',
          '.....WWYYWW.....',
          '.....WWYYWW.....',
          '.....WWYYWW.....',
          '.....WWYYWW.....',
          '......WWWW......',
          '.......WW.......',
          '.......WW.......',
          '.......WW.......',
          '.......WW.......',
          '.......WW.......',
          '................',
        ],
      },
      {
        id: '0809',
        name: '墨水笔',
        emoji: '🖋️',
        grid: [
          '..............WW',
          '.............WWW',
          '............WWW.',
          '...........BBB..',
          '..........BBB...',
          '.........BBB....',
          '........BBB.....',
          '.......BBB......',
          '......BBB.......',
          '.....BBB........',
          '....BBB.........',
          '...BBY..........',
          '..BY............',
          '..Y.............',
          '................',
          '................',
        ],
      },
      {
        id: '0810',
        name: '回形针',
        emoji: '📎',
        grid: [
          '................',
          '....WW....WW....',
          '...WW......WW...',
          '...WW......WW...',
          '...WW......WW...',
          '...WW.W..W.WW...',
          '...WW.W..W.WW...',
          '...WW.W..W.WW...',
          '...WW.W..W.WW...',
          '...WW.WWWW.WW...',
          '...WW......WW...',
          '...WW......WW...',
          '...WW......WW...',
          '....WWWWWWWW....',
          '................',
          '................',
        ],
      },
      {
        id: '0811',
        name: '直尺',
        emoji: '📏',
        grid: [
          '................',
          '................',
          '................',
          '................',
          '................',
          '.YYYYYYYYYYYYYY.',
          '.YNYNYNYNYNYNYN.',
          '.YYYYYYYYYYYYYY.',
          '.YNYNYNYNYNYNYN.',
          '.YYYYYYYYYYYYYY.',
          '................',
          '................',
          '................',
          '................',
          '................',
          '................',
        ],
      },
    ],
  },
  {
    title: '🎮 游戏',
    icons: [
      {
        id: '0901',
        name: '游戏手柄',
        emoji: '🎮',
        grid: [
          '................',
          '................',
          '....BBBBBBBB....',
          '..BBBBBBBBBBBB..',
          '.BBBBBBBBBBBBBB.',
          '.BBBWBBBBBBYYBB.',
          '.BWWWWWBBBBBBBB.',
          '.BBBWBBBBBBRRBB.',
          '.BBBBBBBWWBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBB......BBBB.',
          '.BBB........BBB.',
          '..B..........B..',
          '..B..........B..',
          '................',
          '................',
        ],
      },
      {
        id: '0902',
        name: '摇杆 · 街机复古',
        emoji: '🕹️',
        grid: [
          '................',
          '.....RRRR.......',
          '.....RRRR.......',
          '......WW........',
          '......WW........',
          '......WW........',
          '......WW........',
          '......WW........',
          '....WWWWWW......',
          '..BBBBBBBBBB....',
          '.BBBBBBBBBBBB...',
          'BBBBBBBBBBBBBB..',
          'BBBBBBBBBBBBBB..',
          '.BBBBBBBBBBBB...',
          '..BBBBBBBBBB....',
          '................',
        ],
      },
      {
        id: '0903',
        name: '像素外星怪物 · 复古像素游戏',
        emoji: '👾',
        grid: [
          '................',
          '................',
          '................',
          '..G..........G..',
          '...G........G...',
          '...GGGGGGGGGG...',
          '..GG.GGGGGG.GG..',
          'GGGGGGGGGGGGGGGG',
          'GGGGGGGGGGGGGGGG',
          'GG.GGGGGGGGGG.GG',
          'GG.G........G.GG',
          '...GGG....GGG...',
          '...GG......GG...',
          '................',
          '................',
          '................',
        ],
      },
      {
        id: '0904',
        name: '录像带 · 复古媒体',
        emoji: '📼',
        grid: [
          '................',
          '................',
          '................',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BWWWWWWWWWWWWB.',
          '.BWWWWWWWWWWWWB.',
          '.BWWWWWWWWWWWWB.',
          '.BWWWWWWWWWWWWB.',
          '.BBBBBBBBBBBBBB.',
          '.BBWWBBBBBBWWBB.',
          '.BWWWWBBBBWWWWB.',
          '.BBWWBBBBBBWWBB.',
          '.BBBBBBBBBBBBBB.',
          '................',
          '................',
        ],
      },
      {
        id: '0905',
        name: '软盘 · 老式存档',
        emoji: '💾',
        grid: [
          '................',
          '................',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBWWWWWWWWBB..',
          '..BBWWWWWWWWBB..',
          '..BBWWWWWWWWBB..',
          '..BBWWWWWWWWBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBWWWWWWWWBB..',
          '..BBWWWWWWWWBB..',
          '..BBWWWWWWWWBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBB....',
          '................',
        ],
      },
      {
        id: '0906',
        name: '老式电视机 · 复古主机',
        emoji: '📺',
        grid: [
          '...WW......WW...',
          '....WW....WW....',
          '.....WW..WW.....',
          '.....WWWWWW.....',
          '.WWWWWWWWWWWWWW.',
          '.WBBBBBBBBBWWWW.',
          '.WBBBBBBBBBWYWW.',
          '.WBBBBBBBBBWRWW.',
          '.WBBBBBBBBBWWWW.',
          '.WBBBBBBBBBWGWW.',
          '.WBBBBBBBBBWWWW.',
          '.WBBBBBBBBBWWWW.',
          '.WWWWWWWWWWWWWW.',
          '..WWWWWWWWWWWW..',
          '...WWWWWWWWWW...',
          '................',
        ],
      },
      {
        id: '0907',
        name: '骰子',
        emoji: '🎲',
        grid: [
          '................',
          '................',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWRRWWWWRRWW..',
          '..WWRRWWWWRRWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWRRWWWWW..',
          '..WWWWWRRWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWRRWWWWRRWW..',
          '..WWRRWWWWRRWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '................',
          '................',
        ],
      },
      {
        id: '0908',
        name: '老虎机',
        emoji: '🎰',
        grid: [
          '................',
          '............RRR.',
          '............RRR.',
          '.RRRRRRRRRRR.WW.',
          '.RRRRRRRRRRR.WW.',
          '.RRRRRRRRRRR.WW.',
          '.RWWNWWWNWWR.WW.',
          '.RWWNWWWNWWR.WW.',
          '.RWWNWWWNWWR.WW.',
          '.RWWNWWWNWWR.WW.',
          '.RRRRRRRRRRR....',
          '.RRRRRRRRRRR....',
          '.RRRRRRRRRRR....',
          '.RRRRRRRRRRR....',
          '.BBBBBBBBBBB....',
          '................',
        ],
      },
      {
        id: '0909',
        name: '拼图块',
        emoji: '🧩',
        grid: [
          '................',
          '................',
          '.....GGGG.......',
          '.....GGGG.......',
          '..GGGGGGGGGG....',
          '..GGGGGGGGGG....',
          '..GGGGGGGGGG....',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGG....',
          '..GGGGGGGGGG....',
          '..GGGGGGGGGG....',
          '..GGGGGGGGGG....',
          '................',
          '................',
        ],
      },
      {
        id: '0910',
        name: '台球',
        emoji: '🎱',
        grid: [
          '.....WWWWWW.....',
          '...WWNNNNNNWW...',
          '..WNNNNNNNNNNW..',
          '.WNNNNNNNNNNNNW.',
          'WNNNNNNNNNNNNNNW',
          'WNNNNWWWWWWNNNNW',
          'WNNNNWWNNWWNNNNW',
          'WNNNNWWWWWWNNNNW',
          'WNNNNWWWWWWNNNNW',
          'WNNNNWWNNWWNNNNW',
          'WNNNNWWWWWWNNNNW',
          'WNNNNNNNNNNNNNNW',
          'WNNNNNNNNNNNNNNW',
          '.WNNNNNNNNNNNNW.',
          '..WNNNNNNNNNNW..',
          '...WWNNNNNNWW...',
        ],
      },
      {
        id: '0911',
        name: '奖杯 (同 星星组)',
        emoji: '🏆',
        grid: [
          '................',
          '....YYYYYYYY....',
          '.YY.YYYYYYYY.YY.',
          '.YY.YYYYYYYY.YY.',
          '.YY.YYYYYYYY.YY.',
          '..Y.YYYYYYYY.Y..',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '.....YYYYYY.....',
          '......YYYY......',
          '.......YY.......',
          '.......YY.......',
          '....YYYYYYYY....',
          '...NNNNNNNNNN...',
          '...NNNNNNNNNN...',
          '................',
        ],
      },
    ],
  },
  {
    title: '💻 软件',
    icons: [
      {
        id: '1001',
        name: '笔记本电脑',
        emoji: '💻',
        grid: [
          '................',
          '................',
          '.WWWWWWWWWWWWWW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WWWWWWWWWWWWWW.',
          'WWWWWWWWWWWWWWWW',
          '.WWWWWWWWWWWWWW.',
          '................',
          '................',
        ],
      },
      {
        id: '1002',
        name: '台式显示器',
        emoji: '🖥️',
        grid: [
          '................',
          '.WWWWWWWWWWWWWW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WBBBBBBBBBBBBW.',
          '.WWWWWWWWWWWWWW.',
          '.....WWWWWW.....',
          '.....WWWWWW.....',
          '..WWWWWWWWWWWW..',
          '................',
          '................',
        ],
      },
      {
        id: '1003',
        name: '键盘',
        emoji: '⌨️',
        grid: [
          '................',
          '................',
          '................',
          '................',
          '................',
          '.BBBBBBBBBBBBBB.',
          '.BWWBWWBWWBWWBB.',
          '.BWWBWWBWWBWWBB.',
          '.BBBBBBBBBBBBBB.',
          '.BWWBWWBWWBWWBB.',
          '.BBBBBBBBBBBBBB.',
          '.BWWWWWWWWWWWWB.',
          '.BBBBBBBBBBBBBB.',
          '................',
          '................',
          '................',
        ],
      },
      {
        id: '1004',
        name: '鼠标',
        emoji: '🖱️',
        grid: [
          '................',
          '................',
          '................',
          '.....WWWWWW.....',
          '...WWWWWWWWWW...',
          '..WWWWWWWWWWWW..',
          '..WWWWWNNWWWWW..',
          '..WWWWWNNWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '...WWWWWWWWWW...',
          '....WWWWWWWW....',
          '......WWWW......',
          '................',
          '................',
        ],
      },
      {
        id: '1005',
        name: '电源插头',
        emoji: '🔌',
        grid: [
          '................',
          '...WW..WW.......',
          '...WW..WW.......',
          '...WW..WW.......',
          '..RRRRRRRRRR....',
          '..RRRRRRRRRR....',
          '..RRRRRRRRRR....',
          '..RRRRRRRRRR....',
          '..RRRRRRRRRR....',
          '.....WWWW.......',
          '.....WWWW.......',
          '.....WWWW.......',
          '......WWWW......',
          '......WWWW......',
          '................',
          '................',
        ],
      },
      {
        id: '1006',
        name: '光盘',
        emoji: '📀',
        grid: [
          '................',
          '....BBBBBBBB....',
          '...BBBBBBBBBB...',
          '..BBBBBBBBBBBB..',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          'BBBBBBWWWWBBBBBB',
          'BBBBBBWWWWBBBBBB',
          'BBBBBBWWWWBBBBBB',
          'BBBBBBWWWWBBBBBB',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '..BBBBBBBBBBBB..',
          '...BBBBBBBBBB...',
          '....BBBBBBBB....',
          '................',
        ],
      },
      {
        id: '1007',
        name: 'Wi-Fi 信号',
        emoji: '📶',
        grid: [
          '................',
          '................',
          '................',
          '..........GG....',
          '..........GG....',
          '..........GG....',
          '.......GG.GG....',
          '.......GG.GG....',
          '.......GG.GG....',
          '....GG.GG.GG....',
          '....GG.GG.GG....',
          '....GG.GG.GG....',
          '.GG.GG.GG.GG....',
          '.GG.GG.GG.GG....',
          '.GG.GG.GG.GG....',
          '................',
        ],
      },
      {
        id: '1008',
        name: '无线',
        emoji: '🛜',
        grid: [
          '................',
          '................',
          '.....BBBBBB.....',
          '...BB......BB...',
          '..BB........BB..',
          '.BB..........BB.',
          'BB............BB',
          '................',
          '......BBBB......',
          '....BB....BB....',
          '...BB......BB...',
          '................',
          '................',
          '.......BB.......',
          '.......BB.......',
          '................',
        ],
      },
      {
        id: '1009',
        name: '技术人员',
        emoji: '🧑‍💻',
        grid: [
          '................',
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NYYNNYYN....',
          '....NYYYYYYN....',
          '.....YYYYYY.....',
          '...GGGGGGGGGG...',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGGGG..',
          '.WWWWWWWWWWWWWW.',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '.WNNNNNNNNNNNNW.',
          '.NNNNNNNNNNNNNN.',
        ],
      },
    ],
  },
  {
    title: '🧑‍🎭 角色',
    icons: [
      {
        id: '1101',
        name: '魔法师 · 策划 / 架构师',
        emoji: '🧙',
        grid: [
          '.......BB.......',
          '......BBBB......',
          '......BBBB......',
          '.....BBBBBB.....',
          '.....BBBBBB.....',
          '....BBBBBBBB....',
          '....BBBBBBBB....',
          '...BBBBBBBBBB...',
          '...BBBBBBBBBB...',
          '..RRRRRRRRRRRR..',
          '.RRRRRRRRRRRRRR.',
          '....YYYYYYYY....',
          '....YYNYYNYY....',
          '....YYYYYYYY....',
          '...WWWWWWWWWW...',
          '....WWWWWWWW....',
        ],
      },
      {
        id: '1102',
        name: '超级英雄 · 主力核心成员',
        emoji: '🦸',
        grid: [
          '................',
          '................',
          '....BBBBBBBB....',
          '....BYYNNYYB....',
          '....BYYYYYYB....',
          '.....YYYYYY.....',
          '..RRRRRRRRRRRR..',
          '.RRRRRRRRRRRRRR.',
          '.RRRRRYYYYRRRRR.',
          '.RRRRRYRRYRRRRR.',
          '.RRRRRRRRRRRRRR.',
          '.RRRRRRRRRRRRRR.',
          '.RRRRRRRRRRRRRR.',
          '..RRRRRRRRRRRR..',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1103',
        name: '机器人 · AI / 自动化脚本',
        emoji: '🤖',
        grid: [
          '.......NN.......',
          '......RRRR......',
          '..NNNNNNNNNNNN..',
          '..NBBBBBBBBBBN..',
          '..NBBBBBBBBBBN..',
          '..NBBYYBBYYBBN..',
          '..NBBBBBBBBBBN..',
          '..NBBBBBBBBBBN..',
          '..NNNNNNNNNNNN..',
          '................',
          '..RRRRRRRRRRRR..',
          '.RRRRRRRRRRRRRR.',
          '.RRRYYYYYYYYRRR.',
          '.RRRYRRRRRRYRRR.',
          '.RRRRRRRRRRRRRR.',
          '..RRRR....RRRR..',
        ],
      },
      {
        id: '1104',
        name: '精灵 · 美工 / 创意设计',
        emoji: '🧝',
        grid: [
          '................',
          '.......GG.......',
          '......GGGG......',
          '.....GGGGGG.....',
          '.GGGGGGGGGGGGGG.',
          '.GGYYYYYYYYYYGG.',
          '..GGYYNYYNYYGG..',
          '..GGYYYYYYYYGG..',
          '...GYYYYYYYYG...',
          '....YYYYYYYY....',
          '...GGGGGGGGGG...',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGGGG..',
          '..GGGGGGGGGGGG..',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1105',
        name: '吸血鬼 · 风险方 / 外部对接',
        emoji: '🧛',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NYYYYYYN....',
          '....YYNYYNYY....',
          '....YYYYYYYY....',
          '....YYWYYWYY....',
          '.....YYYYYY.....',
          '...RRRRRRRRRR...',
          '..RRRRRRRRRRRR..',
          '..RRRNNNNNNRRR..',
          '..RRRRRRRRRRRR..',
          '..RRRRRRRRRRRR..',
          '...RRRRRRRRRR...',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1106',
        name: '僵尸 · 遗留旧系统 / 积压任务',
        emoji: '🧟',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NGGGGGGN....',
          '....GGNGGNGG....',
          '....GGGGGGGG....',
          '....GGWGGWGG....',
          '.....GGGGGG.....',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BBBBBBBBBBBB..',
          '..BB..BBBB..BB..',
          '..BB..BBBB..BB..',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1107',
        name: '仙女 · 需求方 / 产品',
        emoji: '🧚',
        grid: [
          '................',
          '......NNNN......',
          '.....YYYYYY.....',
          '.WW...YYYY...WW.',
          '.WWW..YYYY..WWW.',
          '.WWWW..YY..WWWW.',
          '.WWWWW.YY.WWWWW.',
          '..WWWW.YY.WWWW..',
          '...WWW.YY.WWW...',
          '....WW.YY.WW....',
          '.......YY.......',
          '......YYYY......',
          '.....YYYYYY.....',
          '....YYYYYYYY....',
          '......NNNN......',
          '................',
        ],
      },
      {
        id: '1108',
        name: '外星人 · 外部合作方',
        emoji: '👽',
        grid: [
          '................',
          '.....GGGGGG.....',
          '...GGGGGGGGGG...',
          '..GGGGGGGGGGGG..',
          '.GGGGGGGGGGGGGG.',
          '.GGNNNNGGNNNNGG.',
          '.GGNNNNGGNNNNGG.',
          '.GGNNNNGGNNNNGG.',
          '.GGGGGGGGGGGGGG.',
          '..GGGGGGGGGGGG..',
          '...GGGGGGGGGG...',
          '....GGGGGGGG....',
          '.....GGGGGG.....',
          '......GGGG......',
          '................',
          '................',
        ],
      },
      {
        id: '1109',
        name: '幽灵 · 待归档废弃需求',
        emoji: '👻',
        grid: [
          '................',
          '................',
          '.....WWWWWW.....',
          '...WWWWWWWWWW...',
          '..WWWWWWWWWWWW..',
          '.WWWWWWWWWWWWWW.',
          '.WWNNWWWWWWNNWW.',
          '.WWNNWWWWWWNNWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWNNNNNNWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WW.WW.WW.WW.WW.',
          '................',
        ],
      },
      {
        id: '1110',
        name: '超级反派 · 阻碍 / 问题卡点',
        emoji: '🦹',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NNNNNNNN....',
          '....NGGGGGGN....',
          '....GGNGGNGG....',
          '....GGGGGGGG....',
          '..NNNNNNNNNNNN..',
          '.NNNNNNNNNNNNNN.',
          '.NNNNGGGGGGNNNN.',
          '.NNNNGGGGGGNNNN.',
          '.NNNNNNNNNNNNNN.',
          '.NNNNNNNNNNNNNN.',
          '..NNNNNNNNNNNN..',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1111',
        name: '宇航员 · 探索 / 调研任务',
        emoji: '🧑‍🚀',
        grid: [
          '................',
          '....WWWWWWWW....',
          '...WWWWWWWWWW...',
          '...WBBBBBBBBW...',
          '...WBBBBBBBBW...',
          '...WBBBBBBBBW...',
          '...WWWWWWWWWW...',
          '...WWWWWWWWWW...',
          '..WWWWWWWWWWWW..',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWRRWWWWWW.',
          '.WWWWWWRRWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '..WWWW....WWWW..',
          '..WWWW....WWWW..',
        ],
      },
      {
        id: '1112',
        name: '医护 · 运维 / 故障抢修',
        emoji: '🧑‍⚕️',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NYYYYYYN....',
          '....YYNYYNYY....',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '..WWWWWWWWWWWW..',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWRRWWWWWW.',
          '.WWWWRRRRRRWWWW.',
          '.WWWWWWRRWWWWWW.',
          '.WWWWWWRRWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '..WWWW....WWWW..',
          '..WWWW....WWWW..',
        ],
      },
      {
        id: '1113',
        name: '法官 · 评审 / 审核角色',
        emoji: '🧑‍⚖️',
        grid: [
          '................',
          '....WWWWWWWW....',
          '...WWWWWWWWWW...',
          '...WWYYYYYYWW...',
          '...WWYNYYNYWW...',
          '...WWYYYYYYWW...',
          '....YYYYYYYY....',
          '...NNNNNNNNNN...',
          '..NNNNNNNNNNNN..',
          '..NNWWWWWWWWNN..',
          '..NNWWWRRWWWNN..',
          '..NNWWWRRWWWNN..',
          '..NNWWWWWWWWNN..',
          '..NNNNNNNNNNNN..',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1114',
        name: '老师 · 导师 / 文档培训',
        emoji: '🧑‍🏫',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '....NYYYYYYN....',
          '....YNNYYNNY....',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '..BBBBBBBBBBBB..',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBBB.',
          '.BBBBBBBBBBBBYY.',
          '..BBBBBBBBBBYY..',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1115',
        name: '厨师 · 内容制作 / 产出',
        emoji: '🧑‍🍳',
        grid: [
          '....WWWWWWWW....',
          '...WWWWWWWWWW...',
          '..WWWWWWWWWWWW..',
          '..WWWWWWWWWWWW..',
          '...WWWWWWWWWW...',
          '....WWWWWWWW....',
          '....YYYYYYYY....',
          '....YYNYYNYY....',
          '.....YYYYYY.....',
          '..WWWWWWWWWWWW..',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '.WWWWWWWWWWWWWW.',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
      {
        id: '1116',
        name: '飞行员 · 项目负责人',
        emoji: '🧑‍✈️',
        grid: [
          '................',
          '.....NNNNNN.....',
          '....NNNNNNNN....',
          '...NNNNNNNNNN...',
          '...NNYYYYYYNN...',
          '...NNYNYYNYNN...',
          '....YYYYYYYY....',
          '.....YYYYYY.....',
          '..NNNNNNNNNNNN..',
          '.NNWWWWWWWWWWNN.',
          '.NNWWWWRRWWWWNN.',
          '.NNWWWWRRWWWWNN.',
          '.NNWWWWWWWWWWNN.',
          '.NNNNNNNNNNNNNN.',
          '....NN....NN....',
          '....NN....NN....',
        ],
      },
    ],
  },
];
